spring:
  profiles:
    active: dev-6633
---
server:
  port: 6633

file:
  path: /fileUpload/**
  adm:
    path: ..\fileUpload\adm\
    uploadPath: \images\adm
  user:
    path: ..\fileUpload\user\
    uploadPath: \images\user
spring:
  profiles: dev-6633
  application:
    name: user-server

  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.184.107:3306/flowershop_user?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Zheng1125
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    #将session信息存到redis
    store-type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 5000

  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口
    port: 587
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: zjqq520@vip.qq.com
    # 授权码
    password: gjaqjddwxgltdgij
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true
  #mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zj.user.entity
  #开启驼峰命名
  configuration:
    #map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6611/eureka


