server:
  port: 80

spring:
  application:
    name: zuul-server
zuul:
  #重试机制
  retryable: true
  #所有敏感头都不过滤
  sensitive-headers:
  host:
    max-total-connections: 500
    max-per-route-connections: 20
  #配置转发
  routes:
    service-rpc-user:
      path: /user/**
      service-id: user-server
    service-rpc-product:
      path: /product/**
      service-id: product-server
    #上面的简写形式，将某个请求转到哪个服务器上处理
    order-server: /order/**
hystrix:
   command:
     default:
       execution:
         isolation:
             thread:
               timeoutInMilliseconds: 6000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://zj:123456@127.0.0.1:6611/eureka