spring:
  profiles:
    active: dev-6655
---
server:
  port: 6655

file:
  path: /fileUpload/**
  types:
    path: ..\fileUpload\types\
    uploadPath: \images\types
  flower:
    path: ..\fileUpload\flower\
    uploadPath: \images\flower
  store:
    path: ..\fileUpload\store\
    uploadPath: \images\store
  comments:
    path: ..\fileUpload\comments\
    uploadPath: \images\comments
spring:
  profiles: dev-6655
  application:
    name: product-server

  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.184.107:3306/flowershop_flower?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Zheng1125
    type: com.alibaba.druid.pool.DruidDataSource


  #mybatis的相关配置
  mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.zj.product.entity
    #开启驼峰命名
    configuration:
      #map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6611/eureka